# Generated by Django 4.2.16 on 2024-11-06 11:10

import booking.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date', models.DateField(validators=[booking.models.validate_date])),
                ('time', models.CharField(choices=[('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30'), ('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00'), ('20:30', '20:30'), ('21:00', '21:00'), ('21:30', '21:30'), ('22:00', '22:00'), ('22:30', '22:30'), ('23:00', '23:00'), ('23:30', '23:30')], default='19:00', max_length=13)),
                ('num_of_guests', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=4)),
                ('contact_num', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(code='Invalid Number', message='Enter a valid phone number.', regex='^[0-9]+$')])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_reservation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time', '-date'],
                'unique_together': {('date', 'time')},
            },
        ),
    ]
