# Generated by Django 4.2.16 on 2024-10-21 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='updated_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
