# Generated by Django 4.2.16 on 2024-10-21 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['commented_on']},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-posted_on']},
        ),
    ]
